name = "jgarfield"
license = "MIT"
licenselink = "https://github.com/Tri4ce/hugo_theme_jgarfield/blob/master/LICENSE.md"
description = "jgarfield is blog theme for hugo used on the jgarfield.com site."
tags = ["blog"]
features = ["blog"]
min_version = 0.15

[author]
    name = "Justin Garfield"
    homepage = "http://www.jgarfield.com/"

